# See here for image contents: https://github.com/microsoft/vscode-dev-containers/tree/v0.194.3/containers/java-8/.devcontainer/base.Dockerfile

FROM clojure:openjdk-8-lein

RUN useradd -ms /bin/bash vscode
WORKDIR /home/vscode
